"""001_init

Revision ID: f63b7a4e867b
Revises: 
Create Date: 2024-08-03 18:30:10.343707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f63b7a4e867b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gender_types",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=True, comment="Наименование"),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "create_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор создания записи",
        ),
        sa.Column(
            "modify_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего изменения записи",
        ),
        sa.Column(
            "modify_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор последнего изменения записи",
        ),
        sa.Column(
            "deleted",
            mysql.INTEGER(display_width=11),
            server_default="0",
            nullable=False,
            comment="Отметка об удалении записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Тип пола человека",
        mysql_auto_increment="3",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_types",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=True, comment="Наименование типа"
        ),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "create_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор создания записи",
        ),
        sa.Column(
            "modify_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего изменения записи",
        ),
        sa.Column(
            "modify_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор последнего изменения записи",
        ),
        sa.Column(
            "deleted",
            mysql.INTEGER(display_width=11),
            server_default="0",
            nullable=False,
            comment="Отметка об удалении записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Типы пользователей",
        mysql_auto_increment="3",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "users",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("last_name", sa.String(length=255), nullable=True, comment="Фамилия"),
        sa.Column("first_name", sa.String(length=255), nullable=True, comment="Имя"),
        sa.Column(
            "patr_name", sa.String(length=255), nullable=True, comment="Отчество"
        ),
        sa.Column(
            "gender_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="id пола",
        ),
        sa.Column(
            "type_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="id типа пользователя",
        ),
        sa.Column("login", sa.String(length=255), nullable=True, comment="Логин"),
        sa.Column("password", sa.Text(), nullable=True, comment="Пароль"),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "create_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор создания записи",
        ),
        sa.Column(
            "modify_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего изменения записи",
        ),
        sa.Column(
            "modify_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор последнего изменения записи",
        ),
        sa.Column(
            "deleted",
            mysql.INTEGER(display_width=11),
            server_default="0",
            nullable=False,
            comment="Отметка об удалении записи",
        ),
        sa.ForeignKeyConstraint(["create_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["gender_id"], ["gender_types.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["modify_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["type_id"], ["user_types.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
        comment="Пользователи",
        mysql_auto_increment="2",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "document_types",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=True,
            comment="Наименование типа документа",
        ),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "create_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор создания записи",
        ),
        sa.Column(
            "modify_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего изменения записи",
        ),
        sa.Column(
            "modify_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор последнего изменения записи",
        ),
        sa.Column(
            "deleted",
            mysql.INTEGER(display_width=11),
            server_default="0",
            nullable=False,
            comment="Отметка об удалении записи",
        ),
        sa.ForeignKeyConstraint(["create_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modify_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Типы документов",
        mysql_auto_increment="5",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "organizations",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "oid", sa.String(length=255), nullable=True, comment="OID организации"
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=True,
            comment="Наименование организации",
        ),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "create_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор создания записи",
        ),
        sa.Column(
            "modify_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего изменения записи",
        ),
        sa.Column(
            "modify_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор последнего изменения записи",
        ),
        sa.Column(
            "deleted",
            mysql.INTEGER(display_width=11),
            server_default="0",
            nullable=False,
            comment="Отметка об удалении записи",
        ),
        sa.ForeignKeyConstraint(["create_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modify_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("oid"),
        comment="Организации",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "documents",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="id пользователя",
        ),
        sa.Column(
            "type_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="id типа документа",
        ),
        sa.Column(
            "data", sa.Text(), nullable=True, comment="Данные документов в формате JSON"
        ),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "create_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор создания записи",
        ),
        sa.Column(
            "modify_datetime",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего изменения записи",
        ),
        sa.Column(
            "modify_user_id",
            mysql.INTEGER(display_width=11),
            nullable=True,
            comment="Автор последнего изменения записи",
        ),
        sa.Column(
            "deleted",
            mysql.INTEGER(display_width=11),
            server_default="0",
            nullable=False,
            comment="Отметка об удалении записи",
        ),
        sa.ForeignKeyConstraint(["create_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modify_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["type_id"], ["document_types.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Документы пользователей",
        mysql_engine="InnoDB",
    )
    op.create_foreign_key(
        "fk_user_types_create_user_id",
        "user_types",
        "users",
        ["create_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_user_types_modify_user_id",
        "user_types",
        "users",
        ["modify_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_gender_types_create_user_id",
        "gender_types",
        "users",
        ["create_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_gender_types_modify_user_id",
        "gender_types",
        "users",
        ["modify_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    op.drop_table("organizations")
    op.drop_table("document_types")
    op.drop_table("users")
    op.drop_table("user_types")
    op.drop_table("gender_types")
    # ### end Alembic commands ###
